### ISSUE TITLE
是否有vue版本

### ISSUE THREAD

**Issue by ponycloud235** [rachelcao277/LabelImage#9]
为了方便项目集成问的，或者有什么其他思路？  目前项目是前后端分离，前端用nodejs+vue
来自前端菜鸟的疑问

**Comment by phker** [comment]
目前网络上的不是vue版本的么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 下午3:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rachelcao277/LabelImage] 是否有vue版本 (Issue #9)




 
为了方便项目集成问的，或者有什么其他思路？  目前项目是前后端分离，前端用nodejs+vue
 来自前端菜鸟的疑问
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ponycloud235** [comment]
> 目前网络上的不是vue版本的么？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月9日(周二) 下午3:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [rachelcao277/LabelImage] 是否有vue版本 (Issue #9) 为了方便项目集成问的，或者有什么其他思路？ 目前项目是前后端分离，前端用nodejs+vue 来自前端菜鸟的疑问 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没吧，我在github上搜了半天，有关键词吗？

**Comment by ponycloud235** [comment]
找到了个AIlabel 还行，谢谢
